### ISSUE TITLE
3.6.2 fails to build on Debian/Ubuntu armhf

### ISSUE THREAD

**Issue by jbicha** [FreeRDP/FreeRDP#10353]
- freerdp 3.6.2
- OS: Linux
- Ubuntu 24.10, likely also on Debian Unstable
- armhf architecture

freerdp 3.6.2 fails to build on armhf but 3.5.1 successfully built a month ago.

build log excerpt
-----------------
```
/<<PKGBUILDDIR>>/winpr/libwinpr/utils/unwind/debug.c: In function ‘unwind_reason_str’:
/<<PKGBUILDDIR>>/winpr/libwinpr/utils/unwind/debug.c:66:22: error: ‘_URC_FATAL_PHASE2_ERROR’
 undeclared (first use in this function)
   66 |                 case _URC_FATAL_PHASE2_ERROR:
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/winpr/libwinpr/utils/unwind/debug.c:66:22: note: each undeclared
 identifier is reported only once for each function it appears in
…
/<<PKGBUILDDIR>>/winpr/libwinpr/utils/unwind/debug.c:68:22: error: ‘_URC_FATAL_PHASE1_ERROR’
 undeclared (first use in this function)
   68 |                 case _URC_FATAL_PHASE1_ERROR:
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/winpr/libwinpr/utils/unwind/debug.c:70:22: error: ‘_URC_NORMAL_STOP’
 undeclared (first use in this function)
   70 |                 case _URC_NORMAL_STOP:
      |                      ^~~~~~~~~~~~~~~~
```

Build logs
--------------
https://launchpad.net/~jbicha/+archive/ubuntu/arch2/+build/28630946

**Comment by david-geiger** [comment]
Same build issue here for Mageia Cauldron on armv7hl arch.

**Comment by mjt0k** [comment]
This looks like a bug (or, rather, an omission) in gcc.  It provides these definitions in arch-specific unwind.h headers for most platforms, but not for all of them.  In particular, it's missing from armhf and armel unwind.h headers.  On the other hand, these particular defines are not arch-specific in clang, having the same values for all platforms.  Smells like gcc folks just forgot to provide these for arm* and a few other architectures, or maybe this header needs a merge to become non-arch-specific.

The unwind thing is debugging only, so #ifdef'ing-out whole contents of tunwind_reason_str() function in winpr (always returning the "unknown" variant) is a quick bandaid for the build failure.

**Comment by akallabeth** [comment]
@mjt0k assumed such a thing. We do enable `USE_EXECINFO` and `USE_UNWIND` `CMake` variables to enable/disable backtrace support with these.

so, `-DUSE_UNWIND=OFF` will fix that for broken architectures.

**Comment by akallabeth** [comment]
anyone knows if this bug has been reported upstream?

**Comment by mjt0k** [comment]
> so, `-DUSE_UNWIND=OFF` will fix that for broken architectures.

With -DUSE_UNWIND=OFF, the compiler gets -DUSE_UNWIND. And the code checks `#ifdef USE_UNWIND` instead of `#if USE_UNWIND`.  So it doesn't quite work, as far as I can see.

**Comment by mjt0k** [comment]
`-DWINPR_HAVE_UNWIND_H=OFF` (instead of `-DUSE_UNWIND=OFF`) fixes this.

**Comment by akallabeth** [comment]
@mjt0k how so? the symbol is only defined for the compiler if:
1. there is a `unwind.h` header (`WINPR_HAVE_UNWIND_H`)
2. `USE_UNWIND=ON` (default) `CMake` option

**Comment by whitpa** [comment]
I can confirm that this problem still exists in FreeRDP 3.8.0 when compiled on Debian 12 (Bookworm) ARMHF.  I can also confirm that -DWINPR_HAVE_UNWIND_H=OFF works around it.

Moreover, -DWITH_NEON=ON is also broken on ARMHF since - I'm guessing based on the ChangeLog - 3.6.2, because HAVE_NEON is being incorrectly set to OFF on account of ARCH_ARM remaining erroneously unset, because it is incorrectly associated with the symbol "_arm__" rather than "__arm__" (two leading underscores, not one) in cmake/DetectIntrinsicSupport.cmake.  It looks to me as though the definition of ARCH_THUMB is similarly incorrect.

**Comment by akallabeth** [comment]
@whitpa ok, that is interesting, we have architecture builds in the ci https://github.com/FreeRDP/FreeRDP/actions/runs/10868478653

but a pull request is very welcome for the `NEON` detection ;)
as for the `unwind` situation, that library is just broken on these architectures (or completely incompatible with the other architectures)
