### ISSUE TITLE
Build failure on OS X ≤ 10.9: unknown type name 'AudioFormatID'

### ISSUE THREAD

**Issue by ryandesign** [FreeRDP/FreeRDP#4462]
Hi, I'm a developer with the MacPorts project. We recently updated FreeRDP to 2.0.0-rc1, and found that it fails to build on OS X 10.9 or earlier. The error is:

```
./channels/audin/client/mac/audin_mac.c:74:8: error: unknown type name 'AudioFormatID'; did you mean 'AudioFormatInfo'?
static AudioFormatID audin_mac_get_format(const audinFormat* format)
       ^~~~~~~~~~~~~
       AudioFormatInfo
```

`AudioFormatID` was [introduced in OS X 10.10](https://developer.apple.com/documentation/coreaudio/audioformatid).

**Comment by akallabeth** [comment]
@ryandesign Ah, that may indeed be the issue.
I'm currently rewriting the sound channels, so it may take some time to fix this.

**Comment by ivanschou** [comment]
You also need the same define for AudioFormatFlags.

#ifndef AudioFormatID
typedef UInt32 AudioFormatID;
typedef UInt32 AudioFormatFlags;
#endif

**Comment by akallabeth** [comment]
@ivanschou Ok, added that to the branch in #4453
