### PR TITLE
Fix build regressions

### LINKED ISSUE #3268: Can no longer build several modules since #3259
In #3259 there were many cleanups in CMakeLists files.
Examples:
* channels/echo/client
* channels/tsmf/client/alsa
* channels/tsmf/client/gstreamer
* channels/tsmf/client/oss

All fails with messages like
```
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_GetLogLevel'
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_PrintMessage'
```
Adding "freerdp" to the target_link_libraries fixes the issue, however, I don't know if this is intended.

### PR DESCRIPTION
**Pull request by bmiklautz**
FreeRDP didn't build anymore if compiled with -Wl,--no-undefined.

Fixes #3268

### CODE REVIEW

**Comment by bmiklautz** [comment]
@freerdp-bot test.

**Comment by hardening** [comment]
LGTM as far a I can tell
