### ISSUE TITLE
openh264 compilation error: UNSPECIFIED_BIT_RATE undeclared 

### ISSUE THREAD

**Issue by bjoernv** [FreeRDP/FreeRDP#2998]
If FreeRPD is compiled against openh264 library (tested with version 1.1) I get the following error:

$ cmake -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DWITH_PULSE=on -DWITH_JPEG=ON -DWITH_X264=ON -DWITH_OPENH264=ON -DWITH_PCSC=ON .
[...]
$ make
make
[ 41%] Built target winpr
[ 41%] Built target winpr-hash
[ 42%] Built target winpr-makecert-tool
[ 42%] Built target winpr-makecert
[ 42%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/h264.c.o
/var/FreeRDP/libfreerdp/codec/h264.c: In function 'openh264_compress':
/var/FreeRDP/libfreerdp/codec/h264.c:925:34: error: 'UNSPECIFIED_BIT_RATE' undeclared (first use in this function)
   sys->EncParamExt.iMaxBitrate = UNSPECIFIED_BIT_RATE;
                                  ^
/var/FreeRDP/libfreerdp/codec/h264.c:925:34: note: each undeclared identifier is reported only once for each function it appears in
/var/FreeRDP/libfreerdp/codec/h264.c: In function 'openh264_init':
/var/FreeRDP/libfreerdp/codec/h264.c:1123:12: error: 'SDecodingParam' has no member named 'eOutputColorFormat'
   sDecParam.eOutputColorFormat  = videoFormatI420;
            ^
/var/FreeRDP/libfreerdp/codec/h264.c:1124:12: error: 'SDecodingParam' has no member named 'eEcActiveIdc'
   sDecParam.eEcActiveIdc = ERROR_CON_FRAME_COPY;
            ^
libfreerdp/CMakeFiles/freerdp.dir/build.make:2929: recipe for target 'libfreerdp/CMakeFiles/freerdp.dir/codec/h264.c.o' failed
make[2]: **\* [libfreerdp/CMakeFiles/freerdp.dir/codec/h264.c.o] Error 1
CMakeFiles/Makefile2:1115: recipe for target 'libfreerdp/CMakeFiles/freerdp.dir/all' failed
make[1]: **\* [libfreerdp/CMakeFiles/freerdp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by bmiklautz** [comment]
@bjoernv openh264 1.1 is rather old. Please retry with a more recent version.

**Comment by bjoernv** [comment]
FreeRDP compiles with openh264 1.5.0. Because of missing documentation I currently can not test, if H264 functions work with openh264 1.5.0.

**Comment by bmiklautz** [comment]
@bjoernv did I understand this correctly and 1.5.8 **does** work?

**Comment by bjoernv** [comment]
Is openh264 already out? No, FreeRDP found my openh264 1.1 version, "configure" accepted it, but compilation failed. With openh264 I was able to compile. So the minimum requirement of openh264 in FreeRPD should be somewhere between 1.1 and 1.5.

**Comment by bmiklautz** [comment]
@bjoernv sorry I meant 1.5.0. As it seems this is the last official release https://github.com/cisco/openh264/releases (though there is also a tag for 1.5.2).

FreeRDP currently doesn't do any version checks for openh264 at the moment. Speak if the header file is found it is tried to compile/link against.  If I'm not mistaken openh264 version 1.3+ is required.

**Comment by akallabeth** [comment]
working with current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef

**Comment by gramali** [comment]
I am trying to recompile with OPENH264 support. I am getting error message "Could NOT find OpenH264 (missing: OPENH264_LIBRARY OPENH264_INCLUDE_DIR)". Please find attached cmake command and logs. where do I get/install OPENH264_LIBRARY for windows and how to include wfreerdp cmake config.

Cmake Command
c:\GitProjects>cmake -DWITH_OPENH264=ON -DBUILD_SHARED_LIBS=OFF -S . -B C:\GitProjects\FreeRDPBuild\

Cmake Logs
[CMakeOutput.log](https://github.com/FreeRDP/FreeRDP/files/3178226/CMakeOutput.log)
[CMakeError.log](https://github.com/FreeRDP/FreeRDP/files/3178227/CMakeError.log)

**Comment by greenvilleassociates** [comment]
Not nice folks... you have to install h264 first... brew install h264
