### ISSUE TITLE
Can't build on Mac OS X -- function ASN1_FreeEncoded missing 

### ISSUE THREAD

**Issue by dorianj** [FreeRDP/FreeRDP#677]
Bisect says it was caused by 8e224d2f946e69f91216bae81b69bde2ffb495fd ; I can't find a definition for `ASN1_FreeEncoded' in the current source tree; I know the code has compiled for me since that commit, so I don't know what's up. But this happens when I pull the HEAD off git and try to compile.

```
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_MANPAGES=OFF -DWITH_FFMPEG=ON -DWITH_CLIENT=OFF -DWITH_X11=OFF ..

[...]

Soyuz:~/ShortTerm/FreeRDP/build-lib$ make -j1

[...]
Undefined symbols for architecture x86_64:
  "_ASN1_FreeEncoded", referenced from:
      _ASN1_Encode in asn1.c.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[2]: *** [winpr/asn1/libwinpr-asn1.1.0.1.dylib] Error 1
make[1]: *** [winpr/asn1/CMakeFiles/winpr-asn1.dir/all] Error 2
make: *** [all] Error 2
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)
```

Build completes on my Ubuntu machine.

```
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```
