### ISSUE TITLE
Can no longer build several modules since #3259

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#3268]
In #3259 there were many cleanups in CMakeLists files.
Examples:
* channels/echo/client
* channels/tsmf/client/alsa
* channels/tsmf/client/gstreamer
* channels/tsmf/client/oss

All fails with messages like
```
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_GetLogLevel'
FreeRDP-1.99.git.20160331/channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_Get'
channels/tsmf/client/oss/tsmf_oss.c:193: undefined reference to `WLog_PrintMessage'
```
Adding "freerdp" to the target_link_libraries fixes the issue, however, I don't know if this is intended.

**Comment by hardening** [comment]
freerdp ? isn't it winpr ?

**Comment by bmiklautz** [comment]
@weberhofer I wonder about echo and alsa (because I have those in my test build) but the the other two are possible. As @hardening mentioned there are missing dependencies to winpr. I'll have a look.

What cmake config are you using?

Thanks for the report.

**Comment by bmiklautz** [comment]
@weberhofer I just did a clean build with 
```cmake -DWITH_SERVER=ON -DBUILD_TESTING=ON . -DWITH_ALSA=ON -DWITH_OSS=ON ``` and the issues you described didn't show up although echo and tsmf(alsa,oss,gstreamer) where build. Could you do a clean build (git clean -fdx when building from git)?

**Comment by bmiklautz** [comment]
Btw what version of cmake are you using?

**Comment by weberhofer** [comment]
Cmake is version cmake-3.3.2.
I'm building on the openSUSE build server using the following configuration. The builds are always clean as the system is completely new installed before every build. You can have a look at the complete build config at https://build.opensuse.org/package/show/home:weberho:UNSTABLE:RemoteDesktop/freerdp

```bash
%cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
        -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
        -DCMAKE_SKIP_RPATH=ON \
        -DWITH_ALSA=ON \
        -DWITH_CUPS=ON \
        -DWITH_CLIENT=ON \
        -DWITH_SERVER=ON \
        -DWITH_CHANNELS=ON -DSTATIC_CHANNELS=OFF \
        -DWITH_DIRECTFB=OFF \
        -DWITH_FFMPEG=OFF \
        -DWITH_GSM=ON \
        -DWITH_GSTREAMER_1_0=ON \
        -DWITH_IPP=OFF \
        -DWITH_JPEG=ON \
        -DWITH_LIBRARY_VERSIONING=ON \
        -DWITH_OPENSSL=ON \
        -DWITH_PCSC=ON \
        -DWITH_X11=ON \
        -DWITH_XCURSOR=ON \
        -DWITH_XEXT=ON \
        -DWITH_XKBFILE=ON \
        -DWITH_XI=ON \
        -DWITH_XINERAMA=ON \
        -DWITH_XRENDER=ON \
        -DWITH_XV=ON \
        -DWITH_ZLIB=ON \
        -DWITH_SSE2=ON \
        ..
```

**Comment by bmiklautz** [comment]
@weberhofer the culprit might then be -DSTATIC_CHANNELS=OFF

**Comment by bmiklautz** [comment]
@weberhofer I just tried building a0d9969a3030a8056eacbe8b2e7362274d0a9c4b (current master) exactly with the same parameters you are using but I couldn't reproduce the issue. Are you on the latest master?

**Comment by bmiklautz** [comment]
Tested with cmake 3.5.1 and as well as 3.0.2 in an out of tree.

**Comment by bmiklautz** [comment]
@weberhofer when looking at your opensuse build page for freerdp https://build.opensuse.org/package/show/home:weberho:UNSTABLE:RemoteDesktop/freerdp?rev=91 your description says "fork of rdesktop" however for the version you are using (>= 1.0.0) it was a complete re-write so the description isn't really fitting anymore.

**Comment by weberhofer** [comment]
@bmiklautz thanks for notifying me. I have updated this information which came from branching the project...

**Comment by bmiklautz** [comment]
@weberhofer  I think I found the problem. It seems that the default build flags openSUSE use -Wl,--no-undefined which causes the build to fail. I'll create a pull request to fix this when there is some time.

**Comment by weberhofer** [comment]
@bmiklautz thank you. FYI I have removed -DSTATIC_CHANNELS=OFF and collected the log entries again. I didn't see the first lines of failures earlier.

```
/usr/bin/cc  -fPIC -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -msse2 -DWINPR_EXPORTS -DFREERDP_EXPORTS -DNDEBUG -Wno-builtin-macro-redefined -D__FILE__='"$(subst /home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/,,$(subst /home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/,,$(abspath $<)))"' -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libfreerdp-shadow-subsystem.so.2 -o libfreerdp-shadow-subsystem.so.2.0.0 CMakeFiles/freerdp-shadow-subsystem.dir/shadow_subsystem_builtin.c.o CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o -lX11 -lXext -lXext -lXinerama -lXdamage -lXfixes -lXtst libfreerdp-shadow.so.2.0.0 -Wl,-rpath,/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/server/shadow:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/server/common:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/rdtk/librdtk:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/libfreerdp:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/winpr/libwinpr: -Wl,-rpath-link,/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/server/common:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/rdtk/librdtk:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/libfreerdp:/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160331/build/winpr/libwinpr 

CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_input_keyboard_event':
server/shadow/X11/x11_shadow.c:229: undefined reference to `GetVirtualKeyCodeFromVirtualScanCode'
server/shadow/X11/x11_shadow.c:234: undefined reference to `GetKeycodeFromVirtualKeyCode'
server/shadow/X11/x11_shadow.c:229: undefined reference to `GetVirtualKeyCodeFromVirtualScanCode'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_error_handler_for_capture':
server/shadow/X11/x11_shadow.c:682: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:682: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:682: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:682: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:682: undefined reference to `WLog_PrintMessage'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_enum_monitors':
server/shadow/X11/x11_shadow.c:1144: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1144: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1144: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1144: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1144: undefined reference to `WLog_PrintMessage'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_uninit':
server/shadow/X11/x11_shadow.c:1357: undefined reference to `CloseHandle'
server/shadow/X11/x11_shadow.c:1363: undefined reference to `_aligned_free'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_stop':
server/shadow/X11/x11_shadow.c:1393: undefined reference to `MessageQueue_PostQuit'
server/shadow/X11/x11_shadow.c:1395: undefined reference to `CloseHandle'
server/shadow/X11/x11_shadow.c:1394: undefined reference to `WaitForSingleObject'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_message_free':
server/shadow/X11/x11_shadow.c:360: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:360: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:360: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:360: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:360: undefined reference to `WLog_PrintMessage'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_start':
server/shadow/X11/x11_shadow.c:1375: undefined reference to `CreateThread'
server/shadow/X11/x11_shadow.c:1379: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1379: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1379: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1379: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1379: undefined reference to `WLog_PrintMessage'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_screen_grab':
server/shadow/X11/x11_shadow.c:712: undefined reference to `ArrayList_Count'
server/shadow/X11/x11_shadow.c:768: undefined reference to `region16_union_rect'
server/shadow/X11/x11_shadow.c:769: undefined reference to `region16_intersect_rect'
server/shadow/X11/x11_shadow.c:771: undefined reference to `region16_is_empty'
server/shadow/X11/x11_shadow.c:773: undefined reference to `region16_extents'
server/shadow/X11/x11_shadow.c:780: undefined reference to `freerdp_image_copy'
server/shadow/X11/x11_shadow.c:787: undefined reference to `ArrayList_Count'
server/shadow/X11/x11_shadow.c:803: undefined reference to `region16_clear'
server/shadow/X11/x11_shadow.c:795: undefined reference to `ArrayList_GetItem'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_process_message':
server/shadow/X11/x11_shadow.c:863: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:863: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:863: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:857: undefined reference to `region16_union_rect'
server/shadow/X11/x11_shadow.c:831: undefined reference to `region16_union_rect'
server/shadow/X11/x11_shadow.c:863: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:863: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:844: undefined reference to `region16_union_rect'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_thread':
server/shadow/X11/x11_shadow.c:890: undefined reference to `MessageQueue_Event'
server/shadow/X11/x11_shadow.c:894: undefined reference to `GetTickCount64'
server/shadow/X11/x11_shadow.c:898: undefined reference to `GetTickCount64'
server/shadow/X11/x11_shadow.c:901: undefined reference to `WaitForMultipleObjects'
server/shadow/X11/x11_shadow.c:903: undefined reference to `MessageQueue_Event'
server/shadow/X11/x11_shadow.c:903: undefined reference to `WaitForSingleObject'
server/shadow/X11/x11_shadow.c:905: undefined reference to `MessageQueue_Peek'
server/shadow/X11/x11_shadow.c:914: undefined reference to `WaitForSingleObject'
server/shadow/X11/x11_shadow.c:923: undefined reference to `GetTickCount64'
server/shadow/X11/x11_shadow.c:934: undefined reference to `ExitThread'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_base_init':
server/shadow/X11/x11_shadow.c:953: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:953: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:953: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:953: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:953: undefined reference to `WLog_PrintMessage'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_xshm_init':
server/shadow/X11/x11_shadow.c:1078: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1078: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1078: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1078: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1078: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:1087: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1087: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1087: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1096: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1096: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:1096: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1096: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1096: undefined reference to `WLog_GetLogLevel'
CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o: In function `x11_shadow_subsystem_init':
server/shadow/X11/x11_shadow.c:1226: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1226: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1226: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1295: undefined reference to `_aligned_malloc'
server/shadow/X11/x11_shadow.c:1326: undefined reference to `CreateFileDescriptorEventA'
server/shadow/X11/x11_shadow.c:1338: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1338: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1338: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1226: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1226: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:1338: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1338: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:1250: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1250: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1250: undefined reference to `WLog_GetLogLevel'
server/shadow/X11/x11_shadow.c:1275: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1275: undefined reference to `WLog_PrintMessage'
server/shadow/X11/x11_shadow.c:1275: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1275: undefined reference to `WLog_Get'
server/shadow/X11/x11_shadow.c:1275: undefined reference to `WLog_GetLogLevel'

**Comment by bmiklautz** [comment]
@weberhofer can you verify that #3274 also fixes your problem?

**Comment by weberhofer** [comment]
The error lines are the same, but the build-process stops now (before it continued building before stopping) showing the lines with:
```
[   73s] collect2: error: ld returned 1 exit status
[   73s] server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/build.make:131: recipe for target 'server/shadow/libfreerdp-shadow-subsystem.so.2.0.0' failed
[   73s] make[2]: *** [server/shadow/libfreerdp-shadow-subsystem.so.2.0.0] Error 1
[   73s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160407/build'
[   73s] CMakeFiles/Makefile2:4568: recipe for target 'server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/all' failed
[   73s] make[1]: *** [server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/all] Error 2
[   73s] make[1]: *** Waiting for unfinished jobs....
[   73s] [ 92%] Linking C static library libsmartcard-client.a
[   73s] cd /home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160407/build/channels/smartcard/client && /usr/bin/cmake -P CMakeFiles/smartcard-client.dir/cmake_clean_target.cmake
[   73s] cd /home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160407/build/channels/smartcard/client && /usr/bin/cmake -E cmake_link_script CMakeFiles/smartcard-client.dir/link.txt --verbose=1
[   73s] /usr/bin/ar cq libsmartcard-client.a  CMakeFiles/smartcard-client.dir/smartcard_main.c.o CMakeFiles/smartcard-client.dir/smartcard_pack.c.o CMakeFiles/smartcard-client.dir/smartcard_operations.c.o
[   73s] /usr/bin/ranlib libsmartcard-client.a
[   73s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160407/build'
[   73s] [ 92%] Built target smartcard-client
[   73s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/FreeRDP-1.99.git.20160407/build'
[   73s] Makefile:152: recipe for target 'all' failed
[   73s] make: *** [all] Error 2
[   73s] error: Bad exit status from /var/tmp/rpm-tmp.A6SwIC (%build)
[   73s] 
[   73s] 
[   73s] RPM build errors:
[   73s]     Bad exit status from /var/tmp/rpm-tmp.A6SwIC (%build)

**Comment by bmiklautz** [comment]
@weberhofer that's interesting. When testing with the source of my pull request using your spec file on a openSUSE Leap 42.1 (x86_64) it builds find. No error.

**Comment by bmiklautz** [comment]
@weberhofer when using the tar.xz referenced here https://build.opensuse.org/package/show/home:weberho:UNSTABLE:RemoteDesktop/freerdp the problem still exists since it doesn't contain the fixes from PR #3274 (not yet merged to master).

**Comment by weberhofer** [comment]
@bmiklautz thank you for this hint. I have now added the patch to the package and it builds nicely again. Great work! 
The new package should soon be available on OBS.
Btw. if you have any suggestions to the packaging (splitting into the sub-packages, build-options, naming of the sub-packages) your input is highly appreciated. You can also contact me via mail.

**Comment by bmiklautz** [comment]
@weberhofer thank you for the feedback. The fix should be on master soon as well ;). 
Regarding packaging we have plans to update/create a freerdp2 package for Suse/Fedora/$RPM_BASED similar to the outline we use in the debian Package https://github.com/bmiklautz/debian-freerdp2 . The only think that might change is to remove rdtk (as it's not really used).

**Comment by bmiklautz** [comment]
@weberhofer I started working on splitting up the sub-packages and adding build options based on your OBS package similar to the Debian package. Maybe you can contact me via email (for address see FreeRDP commits ;) or drop by in IRC.
