### ISSUE TITLE
[windows] duplicated preprocessor symbols

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#6918]
Essentially, 2.3.2 introduced a variable PEN_FLAG_INVERTED in rdpei (#6569) that conflicts with an existing PEN_FLAG_INVERTED in the win32 api (see [Pen Flags Constants](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/inputmsg/pen-flags-constants)). 

When including [winuser.h](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-pointer_pen_info), the preprocessor will change the line in rdpei.h from PEN_FLAG_INVERTED = 0x0004 to 0x00000002 = 0x0004, which causes the compilation to fail.

**Comment by akallabeth** [comment]
@vscfreire when does that happen? (with current freerdp builds or something custom?)
the flags have been fixed on master, so the next backport is most likely to have this.

**Comment by vscfreire** [comment]
Hello, @akallabeth. Sorry for the delay in the reply.

Just tested and it's still happening on 2.5.0.

I tried simplifying as much as I could in order to reproduce the problem.

So, compiling this simple program:
```c
#include <stdio.h>
#include "freerdp/channels/rdpei.h"

int main(void) {
    printf("Hello, World!\n");
    return 0;
}
```

On Linux, it compiles OK:
```
$ gcc -Wall -Ibuild/include -Iinclude -Ibuild/winpr/include -Iwinpr/include -o freerdp-test freerdp-test.c
$ ./freerdp-test
Hello, World!
$
```

But on Windows, using the MSVC compiler, it fails with an error:
```
> "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.0
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

> cl /Ibuild\include /Iinclude /Ibuild\winpr\include /Iwinpr\include freerdp-test.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

freerdp-test.c
include\freerdp/channels/rdpei.h(77): error C2059: syntax error: 'constant'
>
```

Line 77 in `rdpei.h` is the third definition of the `RDPINPUT_PEN_FLAGS` enum, introduced in #6569:
```c
typedef enum
{
	PEN_FLAG_BARREL_PRESSED = 0x0001,
	PEN_FLAG_ERASER_PRESSED = 0x0002,
	PEN_FLAG_INVERTED = 0x0004
} RDPINPUT_PEN_FLAGS;
```

While the other two names (`PEN_FLAG_BARREL_PRESSED` and `PEN_FLAG_ERASER_PRESSED`) do not exist on Windows, their original names don't have the `_PRESSED` part, the third one (`PEN_FLAG_INVERTED`) exists already with that name (defined in `Winuser.h` - [documentation](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/inputmsg/pen-flags-constants)) with the value `0x00000002`.

So the C preprocessor transforms that line into:
```c
0x00000002 = 0x0004
```

Which obviously causes an error on the compiler.

Altering `rdpei.h` to undefine the constant just before defining the `enum` eliminates the error, which proves that this is caused by a previous definition:
```c
#undef PEN_FLAG_INVERTED
```

Maybe the third value of the `enum` should follow the same naming scheme as the previous two and have the `_PRESSED` suffix? As in:
```c
typedef enum
{
	PEN_FLAG_BARREL_PRESSED = 0x0001,
	PEN_FLAG_ERASER_PRESSED = 0x0002,
	PEN_FLAG_INVERTED_PRESSED = 0x0004
} RDPINPUT_PEN_FLAGS;
```

I'm currently using that `#undef` in my code in order to get it to compile on Windows with MSVC, as a quick workaround, since I never refer to the original `PEN_FLAG_INVERTED` constant.

Thanks!

**Comment by vscfreire** [comment]
Hello, again.

I've noticed that the names have been changed on the `master` branch, as you've mentioned before, to:
```c
typedef enum
{
	RDPINPUT_PEN_FLAG_BARREL_PRESSED = 0x0001,
	RDPINPUT_PEN_FLAG_ERASER_PRESSED = 0x0002,
	RDPINPUT_PEN_FLAG_INVERTED = 0x0004
} RDPINPUT_PEN_FLAGS;
```

Which indeed fixes the problem.

It may be important to backport this change into stable eventually, since it's effectively breaking builds.

Thanks!!

**Comment by akallabeth** [comment]
@vscfreire backport won´t happen as it breaks the stable API. (windows is not a major target for 2.0, `wfreerdp` is lacking a maintainer)
