### ISSUE TITLE
make fails due to "/mnt/richtercloud/sources/FreeRDP/channels/tsmf/client/ffmpeg/tsmf_ffmpeg.c:135:43: error: ‘AV_CPU_FLAG_MMX2’ undeclared (first use in this function)"

### ISSUE THREAD

**Issue by krichter722** [FreeRDP/FreeRDP#2953]
`cmake . && make` fails with 

```
/mnt/richtercloud/sources/FreeRDP/channels/tsmf/client/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_init_audio_stream’:
/mnt/richtercloud/sources/FreeRDP/channels/tsmf/client/ffmpeg/tsmf_ffmpeg.c:135:43: error: ‘AV_CPU_FLAG_MMX2’ undeclared (first use in this function)
  av_set_cpu_flags_mask(AV_CPU_FLAG_SSE2 | AV_CPU_FLAG_MMX2);
                                           ^
/mnt/richtercloud/sources/FreeRDP/channels/tsmf/client/ffmpeg/tsmf_ffmpeg.c:135:43: note: each undeclared identifier is reported only once for each function it appears in
channels/tsmf/client/ffmpeg/CMakeFiles/tsmf-client-ffmpeg-decoder.dir/build.make:54: recipe for target 'channels/tsmf/client/ffmpeg/CMakeFiles/tsmf-client-ffmpeg-decoder.dir/tsmf_ffmpeg.c.o' failed
```

experienced with 1.2.0-beta1+android9-1998-g9520017 on Ubuntu 15.10

**Comment by bmiklautz** [comment]
@krichter722 1.0.0 is really old. This problem should already be fixed in a more recent version.
If you compile yourself try the latest master from github. 
You can also use one of our pre-built packages (https://ci.freerdp.com/job/freerdp-nightly-binaries/)

**Comment by krichter722** [comment]
`1.0.0-7730-g9520017` is the output of `git describe` of the current `master`, but `1.2.0-beta1+android9-1998-g9520017` of `git describe --tags` is more useful. Yet, they both refer to the current HEAD of master (see `man git describe` for an explanation).

**Comment by bmiklautz** [comment]
@krichter722 it wasn't obvious that you are referring to a git commit - distributions versions often look rather similar. The git commit id itself would have been good as well ;).

What version of ffmpeg/libav you are linking against? The nightly builds on 15.10 we are doing don't show this problem.

**Comment by krichter722** [comment]
`1.0.0-9362-g9d4811ee0` works fine out-of-the-box on Ubuntu 16.10.
