### PR TITLE
Add #include to declare winpr_strerror

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes failing builds with Android NDK r26 with freerdp 3.4.0. Noticed in vcpkg.
~~~
/mnt/vcpkg-ci/b/freerdp/src/3.4.0-7803785a45.clean/winpr/libwinpr/sysinfo/cpufeatures/cpu-features.c:148:38: error: call to undeclared function 'winpr_strerror'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                D("Can't open %s: %s\n", pathname, winpr_strerror(errno, ebuffer, sizeof(ebuffer)));
                                                   ^
/mnt/vcpkg-ci/b/freerdp/src/3.4.0-7803785a45.clean/winpr/libwinpr/sysinfo/cpufeatures/cpu-features.c:148:38: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
                D("Can't open %s: %s\n", pathname, winpr_strerror(errno, ebuffer, sizeof(ebuffer)));
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  %d
/mnt/vcpkg-ci/b/freerdp/src/3.4.0-7803785a45.clean/winpr/libwinpr/sysinfo/cpufeatures/cpu-features.c:94:11: note: expanded from macro 'D'
                        printf(__VA_ARGS__);       \
                               ^~~~~~~~~~~
~~~

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@freerdp-bot test please

**Review by akallabeth — APPROVED** [review]
LGTM
