### ISSUE TITLE
SSL_OP_NO_COMPRESSION undeclared error

### ISSUE THREAD

**Issue by kkoh** [FreeRDP/FreeRDP#641]
Dear All,

compile error on "tls.c" 

<< error message >>
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c: In function ‘tls_connect’:
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c:79: error: ‘SSL_OP_NO_COMPRESSION’ undeclared (first use in this function)
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c:79: error: (Each undeclared identifier is reported only once
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c:79: error: for each function it appears in.)
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c: In function ‘tls_accept’:
~/freerdp/FreeRDP/libfreerdp-crypto/tls.c:182: error: ‘SSL_OP_NO_COMPRESSION’ undeclared (first use in this function)

my environment is
- ubuntu 10.04 i386
- openssl 0.9.8 (os built-in library)

I tried to build on ubuntu 12.04 i386, but the same error not found.
(maybe, built-in library openssl 1.0.1)

i want compile on openssl 0.9.8... 

How to solve this issue? (Please help me.)
