### ISSUE TITLE
2.0.0-rc4 doesn't build with libressl

### ISSUE THREAD

**Issue by kapsh** [FreeRDP/FreeRDP#5049]
**Describe the bug**
FreeRDP 2.0.0-rc4 and master cannot be built against libressl (2.7.4 if it matters):

```
[100%] Linking C executable xfreerdp
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libfreerdp/libfreerdp2.so.2.0.0: undefined reference to `SSL_CTX_set_security_level'
collect2: error: ld returned 1 exit status
```
**To Reproduce**
1. mkdir build && cd build
2. cmake .. && make 

**Expected behavior**
It worked in previous 2.0.0-rc3.

**Screenshots**

** Application details
* Version of FreeRDP
* Command line used
* output of `/buildconfig`
* OS version connecting to
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[libressl_build.log](https://github.com/FreeRDP/FreeRDP/files/2605614/libressl_build.log)

**Comment by kapsh** [comment]
Sorry, this didn't work. Looks like libressl has `#define OPENSSL_VERSION_NUMBER 0x20000000L` (very annoying of them) and proper fix could look like: 
```
diff --git a/libfreerdp/crypto/tls.c b/libfreerdp/crypto/tls.c
index 20fde415d..76f51701f 100644
--- a/libfreerdp/crypto/tls.c
+++ b/libfreerdp/crypto/tls.c
@@ -656,7 +656,7 @@ static BOOL tls_prepare(rdpTls* tls, BIO* underlying, SSL_METHOD* method,
 #endif


-#if OPENSSL_VERSION_NUMBER >= 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
+#if OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined(LIBRESSL_VERSION_NUMBER)
 	SSL_CTX_set_security_level(tls->ctx, settings->TlsSecLevel);
 #endif

--
2.19.1

With this patch applied to 2.0.0-rc4 freerdp builds and run (checked with remmina).

**Comment by akallabeth** [comment]
@kapsh thx for the info, indeed annoying. Will update tomorrow

**Comment by kapsh** [comment]
Thank you, it works now.
