### ISSUE TITLE
FreeRDP fails to build under OpenSSL 3.0.0 with error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"

### ISSUE THREAD

**Issue by etna** [FreeRDP/FreeRDP#7286]
As title, FreeRDP from git fails to build against OpenSSL 3.0.0  on Linux. It still builds fine on OpenSSL 1.1.1

Build error produced:
_In file included from /home/etna/Tmpbuilddir/FreeRDP/channels/audin/client/oss/audin_oss.c:36:
In file included from /home/etna/Runtime/Deps/openssl-300/include/openssl/err.h:16:
/home/etna/Runtime/Deps/openssl-300/include/openssl/macros.h:155:4: error: "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"_

OS information:
Debian 11 x64 with git LLVM + Clang 13

CMAKE parameters:
cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/etna/Runtime/Applications/FreeRDP/Build11Sept2021 -DCMAKE_BUILD_TYPE=Release -DCHANNEL_URBDRC=OFF -DWITH_WAYLAND=ON -DWITH_SERVER=ON -DAVCODEC_INCLUDE_DIR=/home/etna/Runtime/Deps/ffmpeg-Build11Sept2021/include -DAVUTIL_INCLUDE_DIR=/home/etna/Runtime/Deps/ffmpeg-Build11Sept2021/include -DSWRESAMPLE_INCLUDE_DIR=/home/etna/Runtime/Deps/ffmpeg-Build11Sept2021/include

Is there any way to get FreeRDP built against OpenSSL 3.0.0? Thanks.

**Comment by akallabeth** [comment]
we have not tried `OpenSSL 3` yet, but pull requests are welcome.

**Comment by akallabeth** [comment]
@etna ok, just compiled current FreeRDP-master (1ee8370f28f1f3542d2559ae23ad670434b303b6) against a custom build of `openssl-3.0.0` tag. Works like a charm.

Can you check your `CMakeCache.txt` for `OPENSSL_*` variables and their value? Might be that some path is still pointing to an old OpenSSL version in your case?

**Comment by etna** [comment]
I will be compiling the latest master tomorrow and will feedback on the outcome.

Since you said it worked for you, I hope to provide some good news when I'm done.

**Comment by etna** [comment]
Unfortunately, I still get the same error when building against OpenSSL 3.0.0:

In file included from /home/etna/Tmpbuilddir/FreeRDP/channels/audin/client/oss/audin_oss.c:36:
In file included from /home/etna/Runtime/Deps/openssl-300/include/openssl/err.h:16:
/home/etna/Runtime/Deps/openssl-300/include/openssl/macros.h:155:4: error: "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
#  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
   ^

This is on a fresh clone of FreeRDP.

**Comment by etna** [comment]
Sorry all, this was my mistake.

channels/audin/client/oss/audin_oss.c has an #include <err.h> but for some reason the build process seems to be picking up OpenSSL's err.h instead of /usr/include/err.h 

Resolved by making minor changes to my  C_INCLUDE_PATH, CPLUS_INCLUDE_PATH and CPPFLAGS.
