### ISSUE TITLE
Undefined symbols: _objc_msgSend

### ISSUE THREAD

**Issue by ryandesign** [FreeRDP/FreeRDP#6163]
**Describe the bug**
FreeRDP 2.0.0 and 2.1.0 do not build on macOS 10.13 and earlier:

```
[ 92%] Linking C shared library libfreerdp-client2.dylib
cd /path/to/build/client/common && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/freerdp-client.dir/link.txt --verbose=ON
/usr/bin/clang -pipe -Os -DNDEBUG -I/opt/local/include -DWINPR_DLL -arch x86_64 -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -compatibility_version 2.0.0 -current_version 2.1.0 -o libfreerdp-client2.2.1.0.dylib -install_name @rpath/libfreerdp-client2.2.dylib CMakeFiles/freerdp-client.dir/client.c.o CMakeFiles/freerdp-client.dir/cmdline.c.o CMakeFiles/freerdp-client.dir/compatibility.c.o CMakeFiles/freerdp-client.dir/file.c.o CMakeFiles/freerdp-client.dir/__/__/channels/client/tables.c.o CMakeFiles/freerdp-client.dir/__/__/channels/client/addin.c.o  -Wl,-rpath,/path/to/build/libfreerdp -Wl,-rpath,/path/to/build/winpr/libwinpr ../../channels/drdynvc/client/libdrdynvc-client.a ../../channels/remdesk/client/libremdesk-client.a ../../channels/rdpsnd/client/librdpsnd-client.a ../../channels/rdpdr/client/librdpdr-client.a ../../channels/rdp2tcp/client/librdp2tcp-client.a ../../channels/rail/client/librail-client.a ../../channels/encomsp/client/libencomsp-client.a ../../channels/cliprdr/client/libcliprdr-client.a ../../channels/video/client/libvideo-client.a ../../channels/urbdrc/client/liburbdrc-client.a ../../channels/rdpsnd/client/librdpsnd-client.a ../../channels/rdpgfx/client/librdpgfx-client.a ../../channels/rdpei/client/librdpei-client.a ../../channels/geometry/client/libgeometry-client.a ../../channels/echo/client/libecho-client.a ../../channels/disp/client/libdisp-client.a ../../channels/audin/client/libaudin-client.a ../../channels/smartcard/client/libsmartcard-client.a ../../channels/serial/client/libserial-client.a ../../channels/printer/client/libprinter-client.a ../../channels/parallel/client/libparallel-client.a ../../channels/drive/client/libdrive-client.a ../../channels/urbdrc/client/libusb/liburbdrc-client-libusb.a ../../channels/rdpsnd/client/mac/librdpsnd-client-mac.a ../../channels/rdpsnd/client/fake/librdpsnd-client-fake.a ../../channels/printer/client/cups/libprinter-client-cups.a ../../channels/audin/client/mac/libaudin-client-mac.a -framework CoreServices ../../channels/urbdrc/client/liburbdrc-client.a /opt/local/lib/libusb-1.0.dylib -framework AVFoundation -framework CoreFoundation /usr/lib/libcups.dylib ../../libfreerdp/libfreerdp2.2.1.0.dylib ../../winpr/libwinpr/libwinpr2.2.1.0.dylib -framework AudioToolbox -framework CoreAudio -framework ApplicationServices
Undefined symbols for architecture x86_64:
  "_objc_msgSend", referenced from:
      _rdpsnd_mac_open in librdpsnd-client-mac.a(rdpsnd_mac.m.o)
      _rdpsnd_mac_set_volume in librdpsnd-client-mac.a(rdpsnd_mac.m.o)
      _rdpsnd_mac_play in librdpsnd-client-mac.a(rdpsnd_mac.m.o)
      _rdpsnd_mac_close in librdpsnd-client-mac.a(rdpsnd_mac.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [client/common/libfreerdp-client2.2.1.0.dylib] Error 1
```

They do build on macOS 10.14 and 10.15.

**To Reproduce**
1. Build FreeRDP 2.0.0 or 2.1.0 on macOS 10.13 or earlier

**Expected behavior**
Successful build

**Application details**
* FreeRDP version: 2.0.0 and 2.1.0
* CMake version: 3.17.2
* Compiler: Apple LLVM version 9.1.0 (clang-902.0.39.2)

**Environment (please complete the following information):**
 - OS: macOS
 - Version/Distribution: High Sierra 10.13.6 
 - Architecture: x86_64

**Additional context**
The problem was reported to MacPorts [here](https://trac.macports.org/ticket/60344).

The problem was not present in 2.0.0-rc4.

It builds successfully if I add `-framework Cocoa` to LDFLAGS but I don't know why it works on 10.14 and 10.15 without doing that.

**Comment by akallabeth** [comment]
could you please add the way you build (`cmake` command line)?
we build every release on mac and it works, so it might be simply missing an option (or using the wrong one)

**Comment by ryandesign** [comment]
From our automated build logs, the [failed build of 2.1.0 on 10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/83474/steps/install-port/logs/stdio) used:

`cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DWITH_ALSA=OFF -DWITH_CCACHE=OFF -DWITH_FFMPEG=ON -DWITH_X11=ON -DWITH_MANPAGES=ON -DWITH_PULSE=OFF -DWITH_JPEG=ON -DWITH_LAME=OFF -DWITH_FAAD2=OFF -DWITH_FAAC=OFF -DWITH_SOXR=OFF -DWITH_CUPS=ON -DWITH_GSSAPI=ON -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" -DCMAKE_OSX_SYSROOT="/" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/FreeRDP-2.1.0`

The [successful build of 2.1.0 on 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/59359/steps/install-port/logs/stdio) used:

`cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DWITH_ALSA=OFF -DWITH_CCACHE=OFF -DWITH_FFMPEG=ON -DWITH_X11=ON -DWITH_MANPAGES=ON -DWITH_PULSE=OFF -DWITH_JPEG=ON -DWITH_LAME=OFF -DWITH_FAAD2=OFF -DWITH_FAAC=OFF -DWITH_SOXR=OFF -DWITH_CUPS=ON -DWITH_GSSAPI=ON -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.14" -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/FreeRDP-2.1.0`

So the only difference is that on 10.13 it uses `-DCMAKE_OSX_SYSROOT="/"` while on 10.14 it uses `-DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk"`; this is necessary since 10.14 and later no longer include headers in /usr/include.

Most of these flags are provided by default by MacPorts for any software that builds using cmake, but can be overridden if necessary.

**Comment by akallabeth** [comment]
@ryandesign interesting are 2 things here:
1. `-DCMAKE_OSX_SYSROOT` is missing for the failing build (I doubt `/` is correct for any OSX version
1. I´d deaktivate kerberos/GSS for any build (there is a reason why we have a sticky issue on our github repo)

**Comment by ryandesign** [comment]
> 1. `-DCMAKE_OSX_SYSROOT` is missing for the failing build (I doubt `/` is correct for any OSX version)

We use `-DCMAKE_OSX_SYSROOT="/"` on 10.13 and earlier in hundreds of other ports that we build with cmake. It works fine on 10.13 and earlier, provided that the command line tools are installed, which they are on our build servers. Switching to` -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk"` does not fix this problem.

> 2. I´d deaktivate kerberos/GSS for any build (there is a reason why we have a sticky issue on our github repo)
> 3. I´d update dependencies and flags, with `2.0.0` HighDPI support for RDP was added which requires `swscale` or `cairo` compiled in to work

Thanks for these suggestions. I can try them but I'm not optimistic that they will fix the problem.

**Comment by akallabeth** [comment]
Ok, so this was not it, checking.
As for the other points, true, will not fix this but if already spotted better tell early.

**Comment by ryandesign** [comment]
True. I'll make a note that we should [deactivate kerberos/GSS](https://trac.macports.org/ticket/60467) and [enable HighDPI support](https://trac.macports.org/ticket/60468).

And thanks for the fix!
