### PR TITLE
sysinfo.c: fix macOS cpu macros

### LINKED ISSUE #13450: Regression since 3.31.0 on macOS: `sysinfo.c: error: 'CPU_TYPE_ARM64' undeclared`
# **Describe the bug**

Regression from https://github.com/FreeRDP/FreeRDP/commit/3d9adc2a4042260408e983c4c1a3628a01f94874 breaking build on PowerPC:

```
:info:build /opt/local/var/macports/build/FreeRDP-25a6c536/work/freerdp-3.31.0/winpr/libwinpr/sysinfo/sysinfo.c: In function 'GetProcessorArchitecture':
:info:build /opt/local/var/macports/build/FreeRDP-25a6c536/work/freerdp-3.31.0/winpr/libwinpr/sysinfo/sysinfo.c:155:22: error: 'CPU_TYPE_ARM64' undeclared (first use in this function); did you mean 'CPU_TYPE_ARM'?
:info:build   155 |                 case CPU_TYPE_ARM64:
:info:build       |                      ^~~~~~~~~~~~~~
:info:build       |                      CPU_TYPE_ARM
:info:build /opt/local/var/macports/build/FreeRDP-25a6c536/work/freerdp-3.31.0/winpr/libwinpr/sysinfo/sysinfo.c:155:22: note: each undeclared identifier is reported only once for each function it appears in
:info:build /opt/local/var/macports/build/FreeRDP-25a6c536/work/freerdp-3.31.0/winpr/libwinpr/sysinfo/sysinfo.c:157:22: error: 'CPU_TYPE_ARM64_32' undeclared (first use in this function); did you mean 'CPU_TYPE_ARM'?
:info:build   157 |                 case CPU_TYPE_ARM64_32:
:info:build       |                      ^~~~~~~~~~~~~~~~~
:info:build       |                      CPU_TYPE_ARM
:info:build make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/sysinfo/sysinfo.c.o] Error 1
```

# **To Reproduce**

Run the build on powerpc-apple-darwin

# **Expected behavior**

`sysctlbyname` is supported in MacOS from ancient time, it should work if code if written correctly.

# **Application details**

* FreeRDP version: 3.31.0

# **Environment (please complete the following information):**

 - OS: macOS
 - Version/Distribution: 10.6.8
 - Architecture: ppc

# **Additional context**

MacPorts

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://github.com/FreeRDP/FreeRDP/issues/13450
Should be uncontroversial. No change for systems where the code already compiled.

### CODE REVIEW

**Review by akallabeth — APPROVED** [review]
LGTM

**Comment by akallabeth** [comment]
@freerdp-bot test

**Review by hardening — APPROVED** [review]
Seems ok

**Comment by barracuda156** [comment]
@akallabeth Thank you!
