### ISSUE TITLE
broken build on freebsd (urbdrc client channel broken in 95522923bab9eb45fb0a3defb16d7e930bfe6fb9 )

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#6393]
broken build on freebsd (urbdrc client channel broken in 95522923bab9eb45fb0a3defb16d7e930bfe6fb9 )

**Comment by sss123next** [comment]
```
[ 81%] Building C object channels/urbdrc/client/libusb/CMakeFiles/urbdrc-client-libusb.dir/libusb_udevman.c.o
/mnt/data/SafeInspectNG/legacy/SafeInspect/src/lib/FreeRDP/channels/urbdrc/client/libusb/libusb_udevman.c:835:20: warning: implicit declaration of function 'libusb_has_capability' is invalid in C99 [-Wimplicit-function-declaration]
        BOOL hasHotplug = libusb_has_capability(LIBUSB_CAP_HAS_HOTPLUG);
                          ^
/mnt/data/SafeInspectNG/legacy/SafeInspect/src/lib/FreeRDP/channels/urbdrc/client/libusb/libusb_udevman.c:835:42: error: use of undeclared identifier 'LIBUSB_CAP_HAS_HOTPLUG'
        BOOL hasHotplug = libusb_has_capability(LIBUSB_CAP_HAS_HOTPLUG);
                                                ^

```

**Comment by sss123next** [comment]
```[ 81%] Building C object channels/urbdrc/client/libusb/CMakeFiles/urbdrc-client-libusb.dir/libusb_udevice.c.o
/mnt/data/SafeInspectNG/legacy/SafeInspect/src/lib/FreeRDP/channels/urbdrc/client/libusb/libusb_udevice.c:112:8: error: use of undeclared identifier 'LIBUSB_CLASS_PHYSICAL'; did you mean 'LIBUSB_DT_PHYSICAL'?
                case LIBUSB_CLASS_PHYSICAL:
                     ^~~~~~~~~~~~~~~~~~~~~
                     LIBUSB_DT_PHYSICAL
/usr/include/libusb.h:81:2: note: 'LIBUSB_DT_PHYSICAL' declared here
        LIBUSB_DT_PHYSICAL = 0x23,
        ^
/mnt/data/SafeInspectNG/legacy/SafeInspect/src/lib/FreeRDP/channels/urbdrc/client/libusb/libusb_udevice.c:804:10: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                        msg = libusb_error_name(ret);
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~


```

**Comment by sss123next** [comment]
second regression introduced in acb77391a2c6735040866bad40955e3aacd961a8

**Comment by rozhuk-im** [comment]
All this definitions in: /usr/include/libusb.h
Add: ```#include <libusb.h>```

**Comment by sss123next** [comment]
on my installation i do not have `LIBUSB_CAP_HAS_HOTPLUG` and `LIBUSB_CLASS_PHYSICAL` in `/usr/include/libusb.h`, which is already included by freerdp.

**Comment by rozhuk-im** [comment]
Update your system: https://github.com/freebsd/freebsd/commit/b7dfc76ba0b22ff0aa7e8264e1ee6b9bafd5bee9
This is in 12 stable last mount ago.

**Comment by akallabeth** [comment]
all these are caused by a `libusb` that is really ancient.
as @rozhuk-im noted, update ;)
