### ISSUE TITLE
Error, GCC 14, incompatible-pointer-types

### ISSUE THREAD

**Issue by xiota** [FreeRDP/FreeRDP#10536]
**Describe the bug**

Fails to build with GCC 14.2.1.  Error is "incompatible-pointer-types".

Git bisect results (first bad 36c3184a0f367c8ffbe695a5d9cda6ea40b6dfad):
```
git bisect start
# status: waiting for both good and bad commits
# good: [de5b7c8e429ea7e9bd005dd4a4484ae9c77de6e9] Merge pull request #10521 from akallabeth/warn-fix-uninit
git bisect good de5b7c8e429ea7e9bd005dd4a4484ae9c77de6e9
# status: waiting for bad commit, 1 good commit known
# bad: [605d390dbaf5b7cfa097fb2a30a67e6a45090b64] Merge pull request #10535 from akallabeth/clang-tidy-fixes
git bisect bad 605d390dbaf5b7cfa097fb2a30a67e6a45090b64
# good: [1b352bf09ae1470f59fea3b1b210d6062db52a43] Merge pull request #10519 from akallabeth/warning-fixes-implicit-int
git bisect good 1b352bf09ae1470f59fea3b1b210d6062db52a43
# bad: [36c3184a0f367c8ffbe695a5d9cda6ea40b6dfad] [warnings] fix clang-tidy issues in libfreerdp
git bisect bad 36c3184a0f367c8ffbe695a5d9cda6ea40b6dfad
# good: [c44f89bc68027959d5fe36ac5491cb8ddc9afd7e] [clang-tidy] disable google-readability-todo
git bisect good c44f89bc68027959d5fe36ac5491cb8ddc9afd7e
# good: [24cd7828c9a98e7f85a7c5772078b49803eb43de] [warnings] fix clang-tidy issues in server
git bisect good 24cd7828c9a98e7f85a7c5772078b49803eb43de
# good: [92e416610af63e528edc6e95534b69aac102de57] [warnings] fix clang-tidy issues in rdtk
git bisect good 92e416610af63e528edc6e95534b69aac102de57
# first bad commit: [36c3184a0f367c8ffbe695a5d9cda6ea40b6dfad] [warnings] fix clang-tidy issues in libfreerdp
```

Relevant log excerpts:

```
-- The C compiler identification is GNU 14.2.1
```

```
/home/main-builder/pkgwork/src/freerdp/libfreerdp/core/gateway/rdg.c: In function ‘BIO_s_rdg’:
/home/main-builder/pkgwork/src/freerdp/libfreerdp/core/gateway/rdg.c:2197:48: error: passing argument 2 of ‘BIO_meth_set_gets’ from incompatible pointer type [-Wincompatible-pointer-types]
 2197 |                 BIO_meth_set_gets(bio_methods, rdg_bio_gets);
      |                                                ^~~~~~~~~~~~
      |                                                |
      |                                                int (*)(BIO *, const char *, int) {aka int (*)(struct bio_st *, const char *, int)}
```
```
/home/main-builder/pkgwork/src/freerdp/libfreerdp/core/gateway/tsg.c: In function ‘BIO_s_tsg’:
/home/main-builder/pkgwork/src/freerdp/libfreerdp/core/gateway/tsg.c:3093:48: error: passing argument 2 of ‘BIO_meth_set_gets’ from incompatible pointer type [-Wincompatible-pointer-types]
 3093 |                 BIO_meth_set_gets(bio_methods, transport_bio_tsg_gets);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                int (*)(BIO *, const char *, int) {aka int (*)(struct bio_st *, const char *, int)}
```

**To Reproduce**

Checkout master.  Configure and build with cmake.  See errors.

**Expected behavior**

Build without error.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Architecture: amd64

**Comment by akallabeth** [comment]
thx, looks like a `const` slipped through, will fix tomorrow.

**Comment by xiota** [comment]
Thank you for updating.  ab9ae66 and d02a30e built successfully.
