### ISSUE TITLE
Build failure on macOS High Sierra: error: expected value in expression

### ISSUE THREAD

**Issue by ryandesign** [FreeRDP/FreeRDP#4160]
The latest code in the FreeRDP 1.1 branch (03ab68318966c3a22935a02838daaea7b7fbe96c) fails to build on macOS 10.13 High Sierra with:

```
cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/build/client/X11 && /opt/local/bin/xsltproc /opt/local/share/xsl/docbook-xsl/manpages/docbook.xsl xfreerdp.1.xml
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/FreeRDP-03ab68318966c3a22935a02838daaea7b7fbe96c/client/Mac/mf_client.m:24:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/FreeRDP-03ab68318966c3a22935a02838daaea7b7fbe96c/client/Mac/mfreerdp.h:22:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_net_FreeRDP/FreeRDP/work/FreeRDP-03ab68318966c3a22935a02838daaea7b7fbe96c/client/Mac/MRDPView.h:20:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
/usr/include/dispatch/dispatch.h:38:45: error: expected value in expression
#if !defined(HAVE_UNISTD_H) || HAVE_UNISTD_H
                                            ^
```

It build fine on macOS 10.12 Sierra.

**Comment by bmiklautz** [comment]
@ryandesign this is due an upgrade in the latest SDK. Already fixed on master with pull request #4142

**Comment by ryandesign** [comment]
> Already fixed on master with pull request #4142

Thanks, I didn't realize that. I had been looking at the stable-1.1 branch which doesn't include those fixes.

**Comment by avgent** [comment]
OK, but how can I do that with macports on High Sierra
sudo port install freerdp
Password:
--->  Computing dependencies for FreeRDP
--->  Building FreeRDP
Error: Failed to build FreeRDP: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_FreeRDP/FreeRDP/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port freerdp failed

**Comment by akallabeth** [comment]
@avgent Wait for the ports to be synced with FreeRDP upstream...

**Comment by bmiklautz** [comment]
@avgent the problem occurs because of an SDK change on MacOS (that is not really right imho). We are working on the next release 2.0 and will only do security fixes on stable-1.1.
I don't use macports myself but they can possibly include the patch referenced in this issue to fix the build.

**Comment by avgent** [comment]
now I am lost, so are we talking hours/days/months here to get freerdp re-working again

**Comment by bmiklautz** [comment]
@avgent master branch should work out of the box. If stable-1.1 is required the macport maintainer might add the referenced fix.

**Comment by ryandesign** [comment]
I already [tried to fix it in MacPorts](https://github.com/macports/macports-ports/commit/aec9e92e6fefda10d0403a358e40abd475f8a29e) but I haven't upgraded to High Sierra yet so I haven't verified that it fixed the problem. If it still doesn't build after you receive the fix by running `sudo port selfupdate`, please [file a MacPorts bug report](https://guide.macports.org/#project.tickets); you can Cc me if you like.

**Comment by avgent** [comment]
@ryandesign THANKS a lot. The sudo port selfupdate followed by sudo port clean freerdp and sudo port install freerdp did the trick... I am back in business
I was definitely not doing the selfupdate part
